/*
*
*
*
*
*
*
*
*
*
*
*
*       DO NOT EDIT THIS FILE
*       For FCC testing purposes!
*
*
*
*
*
*
*
*
*
*
*
*/

const cors = require('cors');
const fs = require('fs');
const path = require('path');

module.exports = function (app) {

  app.use(cors());

  app.get('/_api/get-tests', function(req, res) {
    console.log('loading test file...');
    fs.readdir(path.join(__dirname, 'tests'), function(err, files) {
      if (err) { return res.json({error: 'Error reading test directory'}); }
      const testFiles = files.filter(file => file.substr(-3) === '.js');
      res.json({testFiles: testFiles});
    });
  });

  app.get('/_api/app-info', function(req, res) {
    var hs = Object.keys(res._headers)
      .filter(h => !h.match(/^access-control-\w+/));
    var hObj = {};
    hs.forEach(h => {hObj[h] = res._headers[h]});
    delete res._headers['strict-transport-security'];
    res.json({headers: hObj});
  });

};
